######################################################################
##
## Filename: loopback.udo
## Created on: Wed Feb 11 7:27:56 PM Central Standard Time 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
